config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"
  get "/users/sign_out", to: "events#index"
  get 'tags/:tag', to: 'events#index', as: :tag
  devise_for :users
  resources :events do
    get :join, to: 'events#join', as: 'join'
    get :accept_request, to: 'events#accept_request', as:'accept_request'
    get :reject_request, to: 'events#reject_request', as:'reject_request'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  # add workflow state
  include WorkflowActiverecord
  workflow_column :workflow_state
  workflow do
    state :request_sent do
      event :accept, :transitions_to => :accepted
      event :reject, :transitions_to => :rejected
    end
    state :accepted
    state :rejected
  end
  
  belongs_to :event
  belongs_to :user

  # create attendance and pass event ID and user ID as params
  def self.join_event(user_id, event_id, workflow_state)
    self.create(user_id: user_id, event_id: event_id, workflow_state: workflow_state)
  end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, inverse_of: 'organized_events'

  has_many :attendances
  has_many :users, :through => :attendances

  has_many :taggings
  has_many :tags, through: :taggings

  extend FriendlyId
  friendly_id :title, use: :slugged

  # create tag list
  def all_tags=(names)
    self.tags = names.split(",").map do |t|
      Tag.where(name: t.strip).first_or_create!
    end
  end
  # show tag list
  def all_tags
    tags.map(&:name).join(", ")
  end
  # search the tagged events
  def self.tagged_with(name)
    Tag.find_by_name!(name).events
  end
  # count the number of tags associated with all the events
  def self.tag_counts
    Tag.select("tags.name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end
  # find the event owner
  def self.event_owner(user_id)
    User.find_by id: user_id
  end

  # display the requests for the event owner
  def self.pending_requests(event_id)
    Attendance.where(event_id: event_id, workflow_state: 'request_sent')
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :events, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :organized_events, class_name: "Event", foreign_key: "user_id"

  has_many :attendances
  has_many :events, :through => :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :event_owner!, only: [:edit,:update,:destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create,:update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    if params[:tag]
      @events = Event.tagged_with(params[:tag])
    else
      @events = Event.all
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event_owners = @event.user
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.organized_events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  # GET events/join
  def join
    @attendance = Attendance.join_event(current_user.id, params[:event_id], 'request_sent')
    if @attendance.save
      redirect_to Event.find(params[:event_id]), notice: 'Request Sent'
    end
  end
  # GET events/accept_request
  def accept_request
    @attendance = Attendance.find_by(id: params[:attendance_id]) rescue nil
    @attendance.accept!
    if @attendance.save
      redirect_to Event.find(params[:event_id]), notice: 'Applicant Accepted'
    end
  end
  # GET events/reject_request
  def reject_request
    @attendance = Attendance.where(params[:attendance_id]) rescue nil
    @attendance.reject
    redirect_to Event.find(params[:event_id]), notice: 'Applicant Rejected'
  end

  private
    #authenticate users using devise and check if the current user
    def event_owner!
      authenticate_user!
      if Event.friendly.find(params[:id]).user != current_user
        redirect_to events_path
        flash[:notice] = 'You do not have enough permissions to do this'
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly.find(params[:id])
    end
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_date, :end_date, :location, :agenda, :address, :user_id, :all_tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # to style the tag counts
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
  # method to make a call on the gravatar method using the user's e-mail
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Organized by: <%= event.user.email %></h3>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :agenda %>
    <%= form.text_area :agenda %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :all_tags, "Tags /separate tag by a comma/" %>
    <%= form.text_field :all_tags %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Location</th>
      <th>Agenda</th>
      <th>Address</th>
      <th>Organized by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= l event.start_date, format: :short %></td>
        <td><%= l event.end_date, format: :short %></td>
        <td><%= event.location %></td>
        <td><%= event.agenda %></td>
        <td><%= event.address %></td>
        <td><%= event.user.email %></td>
        <td><%= link_to 'Show', event %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>        
        <% end %>
      </tr>
    <% end %>    
  </tbody>
</table>

<div class="col-lg-4">
  <h3>Search Tags</h3>
  <div>
    <% tag_cloud Event.tag_counts, %w{css1 css2 css3 css4} do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
  </div>
</div>
<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= l @event.start_date, format: :date_format %>
</p>

<p>
  <strong>End date:</strong>
  <%= l @event.end_date, format: :date_format %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Agenda:</strong>
  <%= @event.agenda %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>Organized By:</strong><br>
  <%= @event_owners.email %><br>
  <%= image_tag avatar_url(@event_owners) %>
</p>

<p>
  <strong>Tags:</strong>
  <% @event.all_tags.split(", ").map do |t| %>
    <%= link_to t, tag_path(t) %>
    <%= " | " %>
  <%end%>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>
<hr>
<%= link_to "Join", event_join_path(event_id: @event.id) %>


<% if user_signed_in? && @event.user_id == current_user.id%>
  <label>Join Requests</label>
    <% if Event.pending_requests(@event.id).present? %>
      <% Event.pending_requests(@event.id).each do |p|%>
        <%= image_tag avatar_url(p.user) %>
        <%= p.user.email%>
        <%= link_to 'Accept', event_accept_request_path(event_id: @event.id, attendance_id: p.id) %>
        <%= link_to 'Reject', event_reject_request_path(event_id: @event.id, attendance_id: p.id) %>
        </br>
      <%end%>
    <%else%>
      <p>No Pending Requests for this event</p>
  <%end%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventInventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <ul>
      <li><%= link_to "Root", root_path %></li>
      <% if user_signed_in? %>
      <li><%=link_to "#{current_user.email}" %></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "Login", new_user_session_path %></li>
      <li><%= link_to "SignUp", new_user_registration_path%></li>
      <% end %>
    </ul>
    <%= yield %>
  </body>
</html>